version: '3.8'
services:
    app:
        build: .
        ports:
            - "80:80"
        volumes: 
            - ./app/:/app
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_pass